import type { FilterOption } from "@prisma/client";

// TODO: move to database after signup
export const categoryOptions = [
  {
    fieldId: "freelancer",
    fieldLabel: "Freelancer",
    fieldValue: "freelancer",
    filterCategoryFieldId: "categories",
    filterCategoryLabel: "Category",
    filterCategoryValue: "categories",
    createdAt: new Date(),
  },
  {
    fieldId: "agency",
    fieldLabel: "Agency",
    fieldValue: "agency",
    filterCategoryFieldId: "categories",
    filterCategoryLabel: "Category",
    filterCategoryValue: "categories",
    createdAt: new Date(),
  },
  {
    fieldId: "product_studio",
    fieldLabel: "Product Studio",
    fieldValue: "product_studio",
    filterCategoryFieldId: "categories",
    filterCategoryLabel: "Category",
    filterCategoryValue: "categories",
    createdAt: new Date(),
  },
] as const satisfies FilterOption[];

export const capabilityOptions = [
  {
    fieldId: "ecommerce",
    fieldLabel: "Ecommerce",
    fieldValue: "ecommerce",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "product_management",
    fieldLabel: "Product Management",
    fieldValue: "product_management",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "app_development",
    fieldLabel: "App Development",
    fieldValue: "app_development",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "design",
    fieldLabel: "Design",
    fieldValue: "design",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "ui_ux",
    fieldLabel: "UI/UX Development",
    fieldValue: "ui_ux",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "integration_services",
    fieldLabel: "Integration Services",
    fieldValue: "integration_services",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "branding",
    fieldLabel: "Branding",
    fieldValue: "branding",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "digital_marketing",
    fieldLabel: "Digital Marketing",
    fieldValue: "digital_marketing",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "mobile_development",
    fieldLabel: "Mobile Development",
    fieldValue: "mobile_development",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "ai",
    fieldLabel: "AI",
    fieldValue: "ai",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
  {
    fieldId: "web3-crypto",
    fieldLabel: "Web3 / Crypto",
    fieldValue: "web3-crypto",
    filterCategoryFieldId: "capabilities",
    filterCategoryLabel: "Capabilities",
    filterCategoryValue: "capabilities",
    createdAt: new Date(),
  },
] as const satisfies FilterOption[];

export const frameworkOptions = [
  {
    fieldId: "nextjs",
    fieldLabel: "Next.js",
    fieldValue: "nextjs",
    filterCategoryFieldId: "frameworks",
    filterCategoryLabel: "Frameworks",
    filterCategoryValue: "frameworks",
    createdAt: new Date(),
  },
  {
    fieldId: "nuxtjs",
    fieldLabel: "Nuxt.js",
    fieldValue: "nuxtjs",
    filterCategoryFieldId: "frameworks",
    filterCategoryLabel: "Frameworks",
    filterCategoryValue: "frameworks",
    createdAt: new Date(),
  },
  {
    fieldId: "svelte",
    fieldLabel: "Svelte",
    fieldValue: "svelte",
    filterCategoryFieldId: "frameworks",
    filterCategoryLabel: "Frameworks",
    filterCategoryValue: "frameworks",
    createdAt: new Date(),
  },
  {
    fieldId: "gatsby",
    fieldLabel: "Gatsby",
    fieldValue: "gatsby",
    filterCategoryFieldId: "frameworks",
    filterCategoryLabel: "Frameworks",
    filterCategoryValue: "frameworks",
    createdAt: new Date(),
  },
  {
    fieldId: "angular",
    fieldLabel: "Angular",
    fieldValue: "angular",
    filterCategoryFieldId: "frameworks",
    filterCategoryLabel: "Frameworks",
    filterCategoryValue: "frameworks",
    createdAt: new Date(),
  },
  {
    fieldId: "ember",
    fieldLabel: "Ember",
    fieldValue: "ember",
    filterCategoryFieldId: "frameworks",
    filterCategoryLabel: "Frameworks",
    filterCategoryValue: "frameworks",
    createdAt: new Date(),
  },
  {
    fieldId: "vue",
    fieldLabel: "Vue",
    fieldValue: "vue",
    filterCategoryFieldId: "frameworks",
    filterCategoryLabel: "Frameworks",
    filterCategoryValue: "frameworks",
    createdAt: new Date(),
  },
] as const satisfies FilterOption[];

export const budgetOptions = [
  {
    fieldId: "1000",
    fieldLabel: "$1,000 - $4,999",
    fieldValue: "1000",
    filterCategoryFieldId: "budgets",
    filterCategoryLabel: "Budgets",
    filterCategoryValue: "budgets",
    createdAt: new Date(),
  },
  {
    fieldId: "5000",
    fieldLabel: "$5,000 - $9,999",
    fieldValue: "5000",
    filterCategoryFieldId: "budgets",
    filterCategoryLabel: "Budgets",
    filterCategoryValue: "budgets",
    createdAt: new Date(),
  },
  {
    fieldId: "10000",
    fieldLabel: "$10,000 - $49,999",
    fieldValue: "10000",
    filterCategoryFieldId: "budgets",
    filterCategoryLabel: "Budgets",
    filterCategoryValue: "budgets",
    createdAt: new Date(),
  },
  {
    fieldId: "50000",
    fieldLabel: "$50,000 - $99,999",
    fieldValue: "50000",
    filterCategoryFieldId: "budgets",
    filterCategoryLabel: "Budgets",
    filterCategoryValue: "budgets",
    createdAt: new Date(),
  },
  {
    fieldId: "100000",
    fieldLabel: "$100,000+",
    fieldValue: "100000",
    filterCategoryFieldId: "budgets",
    filterCategoryLabel: "Budgets",
    filterCategoryValue: "budgets",
    createdAt: new Date(),
  },
] as const satisfies FilterOption[];

export const languageOptions = [
  {
    fieldId: "english",
    fieldLabel: "English",
    fieldValue: "english",
    filterCategoryFieldId: "languages",
    filterCategoryLabel: "Languages Spoken",
    filterCategoryValue: "languages",
    createdAt: new Date(),
  },
  {
    fieldId: "portugese",
    fieldLabel: "Portuguese",
    fieldValue: "portugese",
    filterCategoryFieldId: "languages",
    filterCategoryLabel: "Languages Spoken",
    filterCategoryValue: "languages",
    createdAt: new Date(),
  },
  {
    fieldId: "spanish",
    fieldLabel: "Spanish",
    fieldValue: "spanish",
    filterCategoryFieldId: "languages",
    filterCategoryLabel: "Languages Spoken",
    filterCategoryValue: "languages",
    createdAt: new Date(),
  },
  {
    fieldId: "chinese",
    fieldLabel: "Chinese",
    fieldValue: "chinese",
    filterCategoryFieldId: "languages",
    filterCategoryLabel: "Languages Spoken",
    filterCategoryValue: "languages",
    createdAt: new Date(),
  },
  {
    fieldId: "french",
    fieldLabel: "French",
    fieldValue: "french",
    filterCategoryFieldId: "languages",
    filterCategoryLabel: "Languages Spoken",
    filterCategoryValue: "languages",
    createdAt: new Date(),
  },
  {
    fieldId: "japanese",
    fieldLabel: "Japanese",
    fieldValue: "japanese",
    filterCategoryFieldId: "languages",
    filterCategoryLabel: "Languages Spoken",
    filterCategoryValue: "languages",
    createdAt: new Date(),
  },
  {
    fieldId: "german",
    fieldLabel: "German",
    fieldValue: "german",
    filterCategoryFieldId: "languages",
    filterCategoryLabel: "Languages Spoken",
    filterCategoryValue: "languages",
    createdAt: new Date(),
  },
] as const satisfies FilterOption[];

export const regions = [
  {
    fieldId: "asia",
    fieldLabel: "Asia",
    fieldValue: "asia",
    filterCategoryFieldId: "regions",
    filterCategoryLabel: "Region",
    filterCategoryValue: "regions",
    createdAt: new Date(),
  },
  {
    fieldId: "australia",
    fieldLabel: "Australia and New Zealand",
    fieldValue: "australia",
    filterCategoryFieldId: "regions",
    filterCategoryLabel: "Region",
    filterCategoryValue: "regions",
    createdAt: new Date(),
  },
  {
    fieldId: "europe",
    fieldLabel: "Europe",
    fieldValue: "europe",
    filterCategoryFieldId: "regions",
    filterCategoryLabel: "Region",
    filterCategoryValue: "regions",
    createdAt: new Date(),
  },
  {
    fieldId: "latin_america",
    fieldLabel: "Latin America",
    fieldValue: "latin_america",
    filterCategoryFieldId: "regions",
    filterCategoryLabel: "Region",
    filterCategoryValue: "regions",
    createdAt: new Date(),
  },
  {
    fieldId: "middle_east",
    fieldLabel: "Middle East",
    fieldValue: "middle_east",
    filterCategoryFieldId: "regions",
    filterCategoryLabel: "Region",
    filterCategoryValue: "regions",
    createdAt: new Date(),
  },
  {
    fieldId: "north_america",
    fieldLabel: "North America",
    fieldValue: "north_america",
    filterCategoryFieldId: "regions",
    filterCategoryLabel: "Region",
    filterCategoryValue: "regions",
    createdAt: new Date(),
  },
  {
    fieldId: "remote",
    fieldLabel: "Remote",
    fieldValue: "remote",
    filterCategoryFieldId: "regions",
    filterCategoryLabel: "Region",
    filterCategoryValue: "regions",
    createdAt: new Date(),
  },
] as const satisfies FilterOption[];

export const filterOptions = [
  ...categoryOptions,
  ...capabilityOptions,
  ...frameworkOptions,
  ...budgetOptions,
  ...languageOptions,
  ...regions,
] as const satisfies FilterOption[];
